<a href="https://colab.research.google.com/github/Saibhossain/pytorch-foundations-and-projects/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch



In [6]:
torch.range(1,11)

/tmp/ipython-input-1341862064.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1,11)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [4]:
torch.arange(1,11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
torch.arange(start=1,end=11,step=1)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# tensor datatype